version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis_broker
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes --requirepass ""
    volumes:
      - redis_data:/data
    networks:
      - job-network

  mongo:
    image: mongo:6-jammy
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - job-network

  backend:
    build: ./backend
    container_name: job_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - redis
      - mongo
    networks:
      - job-network

  worker:
    build: ./backend
    container_name: job_worker
    command: python -u -m app.worker
    volumes:
      - ./backend:/app
    environment:
      - REDIS_HOST=redis
      - MONGO_URL=mongodb://mongo:27017
      - WORKER_ID=worker-node-1
    depends_on:
      - redis
      - mongo
      - backend
    networks:
      - job-network

  frontend:
    build: ./frontend
    container_name: job_dashboard
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - job-network

networks:
  job-network:
    driver: bridge

volumes:
  redis_data:
  mongo_data:
